<a href="https://colab.research.google.com/github/Ldkhanhduy/baitaptrenlop_k3/blob/main/Numpy_k3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as d

Cau 1

In [ ]:
n=abs(int(input('nhap so phan tu cho vector x:')))
x=d.random.randint(-10,10,n)
print('x=',x)

nhap so phan tu cho vector x:5
x= [ 1  1  1  9 -2]


Cau 2

In [ ]:
x1=x.copy()
for i in range(len(x1)):
  if x1[i]<0:
    x1[i]*=(-1)
print('sin(x)=',d.sin(x1))
print('cos(x)=',d.cos(x1))
print('sqrt(x)=',d.sqrt(x1))
print('log(x)=',d.log(x1))

sin(x)= [0.84147098 0.84147098 0.84147098 0.41211849 0.90929743]
cos(x)= [ 0.54030231  0.54030231  0.54030231 -0.91113026 -0.41614684]
sqrt(x)= [1.         1.         1.         3.         1.41421356]
log(x)= [0.         0.         0.         2.19722458 0.69314718]


Cau 3

In [ ]:
print('sin(x)=',d.round_(d.sin(x1),1,None))
print('cos(x)=',d.round_(d.cos(x1),1,None))
print('sqrt(x)=',d.round_(d.sqrt(x1),1,None))
print('log(x)=',d.round_(d.log(x1),1,None))

sin(x)= [0.8 0.8 0.8 0.4 0.9]
cos(x)= [ 0.5  0.5  0.5 -0.9 -0.4]
sqrt(x)= [1.  1.  1.  3.  1.4]
log(x)= [0.  0.  0.  2.2 0.7]


Cau 4

In [ ]:
m=abs(int(input('nhap so hang cho ma tran:')))
n=abs(int(input('nhap so cot cho ma tran:')))
matran=d.random.randint(-10,10,m*n)
matran=d.reshape(matran,(m,n))
print(matran)
matranx=matran.copy()
print(matranx)
for i in range(len(matranx)):
  for j in range(len(matranx[i])):
    if matranx[i,j]<0:
      matranx[i,j]*=(-1)
print('sin(x)=',d.round_(d.sin(matranx),3,None))
print('cos(x)=',d.round_(d.cos(matranx),3,None))
print('sqrt(x)=',d.round_(d.sqrt(matranx),3,None))
print('log(x)=',d.round_(d.log(matranx),3,None))

nhap so hang cho ma tran:3
nhap so cot cho ma tran:3
[[ 6  6  6]
 [-6  5  9]
 [ 1 -8 -4]]
[[ 6  6  6]
 [-6  5  9]
 [ 1 -8 -4]]
sin(x)= [[-0.279 -0.279 -0.279]
 [-0.279 -0.959  0.412]
 [ 0.841  0.989 -0.757]]
cos(x)= [[ 0.96   0.96   0.96 ]
 [ 0.96   0.284 -0.911]
 [ 0.54  -0.146 -0.654]]
sqrt(x)= [[2.449 2.449 2.449]
 [2.449 2.236 3.   ]
 [1.    2.828 2.   ]]
log(x)= [[1.792 1.792 1.792]
 [1.792 1.609 2.197]
 [0.    2.079 1.386]]


In [ ]:
v=(100-(-100))*d.random.random_sample(1000)+(-100)
print('v=',v)
f=3*d.power(v,2)-d.multiply(v,2)-4
print('f(x)=',f)
print('cos(f(x))=',d.cos(f))
print('sin(f(x))=',d.sin(f))

v= [ 4.37659617e+01 -2.07458395e+01 -6.23155421e+01 -5.22281453e+01
  1.38792942e+01 -1.01314108e+01  3.26042076e+01 -3.61020929e+01
  9.15608470e+01 -5.84199334e+01 -4.31541610e+00 -7.72183667e+01
 -3.85183772e+01  3.06811268e+01  6.67721668e+01 -2.27458209e+01
  8.45589044e+01  9.92326285e+01 -9.67471712e+01  2.46223801e+01
 -6.83843548e+01 -3.46126335e+01 -8.28910892e+00  3.62137056e+01
 -1.92898410e+01  2.93363506e+01 -9.46190716e+01  9.30679459e+01
  7.53491282e+01 -5.55684966e+01 -9.72411454e+00 -1.10416180e+01
 -7.45668206e+01  8.10320759e+01  8.09382002e+01  6.58716117e+01
  3.09969493e+01 -1.10031921e+01  9.66217690e+01  6.04976635e+01
  3.60768044e+01  3.87570432e+01  8.55326594e+01  4.79576513e+01
  5.06086235e+01  4.53981804e+00  9.04483681e+01  8.13469586e+01
  7.57720816e+01 -7.01325247e+01 -4.79325382e+01 -1.37142255e+01
  1.98341416e+01 -9.58985513e+00  1.10296333e+01 -5.46698856e+01
 -7.41521616e+01  7.02508505e+00 -9.12076054e+01  8.55466712e+01
 -9.26876158e+01  3.45